config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  root 'pages#home'
  get '/about' => 'pages#about'
  get '/thanks' => 'pages#thanks'

  resources :signups, only: [:new, :create]
  post "signups/new"

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/signup.rb
class Signup < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
end

app/controllers/signups_controller.rb
class SignupsController < ApplicationController
    def new
        if signup_params
            # If data submitted already by the form we call the create method
            create
            return
        end
        @signup = Signup.new
        render 'new' # call it explicit
    end

    def create
        @signup = Signup.new(signup_params)
        if @signup.save
            redirect_to :thanks
        else
            render 'new'
        end
    end

    private

    def signup_params
        if params[:signup].nil? || params[:signup].empty?
            return false
        else
            params.require(:signup).permit(:first_name, :email, :commit)
        end
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/signups_helper.rb
module SignupsHelper
end

app/views/layouts/_footer.html.erb
<footer class="footer">
  <p>&copy; 2020 Petr Janík</p>
</footer>

app/views/layouts/_menu.html.erb
<%= image_tag "menu-black.svg", class: "menu-icon--open", :onClick => "openMenu()" %>

<div class="menu" id="menu">
  <ul class="menu-list">
    <%= image_tag "close-white.svg", class: "menu-icon--close", :onClick => "closeMenu()" %>
    <li><%= link_to "Home", :root %></li>
    <li><%= link_to "About", :about %></li>
    <li><%= link_to "Contact", new_signup_path %></li>
  </ul>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Stories</title>

    <link href="https://fonts.googleapis.com/css2?family=Roboto:wght@100;300;400;700&display=swap" rel="stylesheet">

    <link rel="apple-touch-icon" sizes="57x57" href="/apple-icon-57x57.png">
    <link rel="apple-touch-icon" sizes="60x60" href="/apple-icon-60x60.png">
    <link rel="apple-touch-icon" sizes="72x72" href="/apple-icon-72x72.png">
    <link rel="apple-touch-icon" sizes="76x76" href="/apple-icon-76x76.png">
    <link rel="apple-touch-icon" sizes="114x114" href="/apple-icon-114x114.png">
    <link rel="apple-touch-icon" sizes="120x120" href="/apple-icon-120x120.png">
    <link rel="apple-touch-icon" sizes="144x144" href="/apple-icon-144x144.png">
    <link rel="apple-touch-icon" sizes="152x152" href="/apple-icon-152x152.png">
    <link rel="apple-touch-icon" sizes="180x180" href="/apple-icon-180x180.png">
    <link rel="icon" type="image/png" sizes="192x192" href="/android-icon-192x192.png">
    <link rel="icon" type="image/png" sizes="32x32" href="/favicon-32x32.png">
    <link rel="icon" type="image/png" sizes="96x96" href="/favicon-96x96.png">
    <link rel="icon" type="image/png" sizes="16x16" href="/favicon-16x16.png">
    <link rel="manifest" href="/manifest.json">
    <meta name="msapplication-TileColor" content="#ffffff">
    <meta name="msapplication-TileImage" content="/ms-icon-144x144.png">
    <meta name="theme-color" content="#ffffff">

    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= render 'layouts/menu' %>

    <%= yield %>

    <%= render 'layouts/footer' %>
  </body>
</html>

app/views/pages/about.html.erb
<section class="main-section-about">
  <div class="main-section-about__contents">
    <h1 class="title">Relive your favorite memories</h1>
  </div>
</section>
<section class="supporting-section">
  <h2 class="subheading">No more sorting through photos</h2>
  <p>Stories automatically finds your best photos and creates a new travelogue. This way you can capture and share your special moments in fresh new ways.</p>
  <%= link_to "Sign up", new_signup_path, class: "btn btn--signup" %>
</section>

app/views/pages/home.html.erb
<section class="main-section-home">
  <div class="main-section-home__contents">
    <h1 class="title">Create and share Stories</h1>
    <%= link_to "Learn more", :about, class: "btn" %>
  </div>
</section>
<section class="supporting-section">
  <h2 class="subheading">Relive and share your adventures</h2>
  <p>Stories automatically creates a digital journal filled with only your best photos.</p>
</section>
<section class="secondary-section">
</section>
<section class="discover-section">
  <h2 class="subheading">Discover Stories</h2>
  <%= link_to "Learn more", :about, class: "btn" %>
</section>

app/views/pages/thanks.html.erb
<section class="main-section-signup">
  <div class="main-section-signup__contents">
    <h1 class="title">Thanks. We'll be in touch.</h1>
  </div>
</section>

app/views/signups/new.html.erb
<section class="main-section-signup">
  <div class="main-section-signup__contents">
    <h1 class="title">Get the latest updates from Stories</h1>

    <%= form_for @signup, :url => {:action => :new}, :html => {:class => "signup-form"} do |f| %>
    <div class="form-group">
      <%= f.label :first_name, class: "form-label" %>
      <%= f.text_field :first_name, class: "form-input" %>
    </div>

    <div class="form-group">
      <%= f.label :email, class: "form-label" %>
      <%= f.email_field :email, class: "form-input" %>
    </div>

    <%= f.submit "Join", class: "btn--join" %>

    <% end %>
  </div>
</section>